### ISSUE TITLE
Feature Request: history of contenthash

### ISSUE THREAD

**Issue by livid** [Planetable/ENSKit#3]
It would be awesome if we could fetch the history of all contenthash an ENS has in history.

Since every historical contenthash is a transaction like this:

https://etherscan.io/tx/0xaf87d7a73ed79fb063ada2a36ef49e95ca773caa09d6f499345e173a31fc2c2c

Above is vitalik.eth's latest setContentHash call.

So if we can get a list of all setContentHash calls, we can have all historical contenthash.

**Comment by livid** [comment]
If an ENS gets compromised for its contenthash, we can see when and what happened clearly.

**Comment by stdc105** [comment]
After some preliminary research, it seems doable with events.

On EVM level, events are represented by logs. Retrieve logs by calling `eth_getLogs` on this [JSON-RPC API spec](https://ethereum.github.io/execution-apis/api-documentation/).

How events are encoded to logs is explained in this [Solidity documentation](https://docs.soliditylang.org/en/v0.8.16/abi-spec.html#events].

When the contenthash of an ENS is changed, the resolver emits a `ContenthashChanged` event, as shown in the [latest contract code](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/profiles/ContentHashResolver.sol), and [Etherscan contract code (see line 51)](https://etherscan.io/address/0xd3ddccdd3b25a8a7423b5bee360a42146eb4baf3#code).

**Comment by stdc105** [comment]
It is very unlikely to query ENS changes by executing `eth_getLogs` on Cloudflare Ethereum Gateway, as only data in latest 128 blocks can be fetched. The following command should verify the problem:
```
> curl -XPOST -H "content-type: application/json" -H "accept: application/json" -d '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address":"0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41","topics":["0xe379c1624ed7e714cc0937528a32359d69d5281337765313dba4e081b72d7578","0xee6c4522aab0003e8d14cd40a6af439055fd2577951148c14b6cea9a53475835"]}],"id":1}' https://cloudflare-eth.com/
{"jsonrpc":"2.0","error":{"code":-32043,"message":"Requested data cannot be older than 128 blocks."},"id":1}
```

(In the above command, `0xe379c1624ed7e714cc0937528a32359d69d5281337765313dba4e081b72d7578` is the event type, and `0xee6c4522aab0003e8d14cd40a6af439055fd2577951148c14b6cea9a53475835` is the namehash of vitalik.eth)

Sending a slightly modified request to Infura API gave me all the logs in question.
```
curl -XPOST -H "content-type: application/json" -H "accept: application/json" -d '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address":"0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41","topics":["0xe379c1624ed7e714cc0937528a32359d69d5281337765313dba4e081b72d7578","0xee6c4522aab0003e8d14cd40a6af439055fd2577951148c14b6cea9a53475835"],"fromBlock":"earliest","toBlock":"latest"}],"id":1}' https://mainnet.infura.io/v3/4cd2c3b40ea8423fa889fc479e05f082
{"jsonrpc":"2.0","id":1,"result":[{"address":"0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41","blockHash":"0xa7f70045c7b8efef3d486e698e7eeb977334491d5531dd218bd985b788c6098e","blockNumber":"0xb50280","data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000","logIndex":"0x13a","removed":false,"topics":["0xe379c1624ed7e714cc0937528a32359d69d5281337765313dba4e081b72d7578","0xee6c4522aab0003e8d14cd40a6af439055fd2577951148c14b6cea9a53475835"],"transactionHash":"0x160ef4492c731ac6b59beebe1e234890cd55d4c556f8847624a0b47125fe4f84","transactionIndex":"0x71"},...]
```

**Comment by stdc105** [comment]
Done in #4. I will release 0.5 tomorrow after some more integration attempts.
